language: node_js
node_js: 
- "0.10"
before_install: 
- npm install -g grunt-cli
env: 
  secure: qevUL+1b5tpXetJUXjSroS9cHmHiP0YGEEicQJQgwn5DitTKHOw1A7RNILxQvaYHvJiTpEel+hZ2rGDOK0DsfyeMWYQ0f0knBRLufZh9pembbzn+1B2Ao4cB5mKrjKqHP+7ODNmK8GFg+zIINoriAK5ldjbIvGoKWB4YOLNm5Yk=
