language: node_js
node_js: 
- "0.10"
before_install: 
- npm install -g grunt-cli
env: 
  secure: lTdcgqysluNBz9XSxSgFWWLsjgrMeCdcty/UtoyxaKdeuMZ4cLE6LhUo1wl9HEwUWCdBJ2IVr0K5/uOSrRVCEBGjfuBBIp3o9unMAqr51ti4CRfq5ggex6HoYI2DYqx4p6KWF1lUg5QQagEPmEL8C6/tLpmi5SZDz8wVB7/Ld7c=
